#!/bin/bash
# Build helper script for LEGO Star Wars decompilation
# Handles the dtk split workaround automatically

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "=== LEGO Star Wars Decompilation Build ==="
echo

# Clean build if requested
if [ "$1" = "clean" ]; then
    echo "Cleaning build directory..."
    rm -rf build/
fi

# Step 1: Configure and download tools
echo "[1/3] Running configure.py and downloading tools..."
python3 configure.py
# Download tools by running ninja with a tools target
if [ ! -f "build/tools/dtk" ]; then
    echo "Downloading build tools (first time only)..."
    ninja build/tools/dtk build/tools/objdiff-cli build/tools/wibo build/binutils build/compilers 2>&1 | grep -E "(Downloading|TOOL)" || true
fi

# Step 2: Check if split is needed
if [ ! -f "build/GL5E4F/config.json" ] || [ "config/GL5E4F/config.yml" -nt "build/GL5E4F/config.json" ]; then
    echo "[2/3] Running dtk split (this takes ~3 minutes)..."
    echo "Note: dtk may show warnings/errors but will complete successfully."
    echo
    
    # Run split - wait for it to complete
    if ! timeout 300 build/tools/dtk dol split config/GL5E4F/config.yml build/GL5E4F 2>&1; then
        echo "Warning: dtk split may have encountered issues, but continuing..."
    fi
    
    # Fix symbols.txt if it has duplicates
    if [ -f "config/GL5E4F/symbols.txt" ]; then
        echo
        echo "Fixing symbols.txt..."
        python3 tools/fix_symbols.py
        
        echo "Applying documented symbol names..."
        python3 tools/add_documented_symbols.py
        
        echo "Applying batch string renames..."
        python3 tools/batch_rename_strings.py
    fi
    
    # Create config.json if it doesn't exist
    if [ ! -f "build/GL5E4F/config.json" ]; then
        echo "Creating config.json..."
        mkdir -p build/GL5E4F
        cat > build/GL5E4F/config.json << 'EOF'
{
  "version": "1.8.3",
  "name": "main",
  "module_id": 0,
  "ldscript": "build/GL5E4F/ldscript.lcf",
  "entry": "__start",
  "units": [
    {"object": "build/GL5E4F/obj/auto_07_8040B300_sdata2.o", "name": "auto_07_8040B300_sdata2", "autogenerated": true, "code_size": 0, "data_size": 2624},
    {"object": "build/GL5E4F/obj/auto_06_8040A2C0_sbss.o", "name": "auto_06_8040A2C0_sbss", "autogenerated": true, "code_size": 0, "data_size": 4132},
    {"object": "build/GL5E4F/obj/auto_05_80407A40_sdata.o", "name": "auto_05_80407A40_sdata", "autogenerated": true, "code_size": 0, "data_size": 10368},
    {"object": "build/GL5E4F/obj/auto_04_801FD080_bss.o", "name": "auto_04_801FD080_bss", "autogenerated": true, "code_size": 0, "data_size": 2140604},
    {"object": "build/GL5E4F/obj/auto_03_801B0640_data.o", "name": "auto_03_801B0640_data", "autogenerated": true, "code_size": 0, "data_size": 313888},
    {"object": "build/GL5E4F/obj/auto_02_8018CB00_rodata.o", "name": "auto_02_8018CB00_rodata", "autogenerated": true, "code_size": 0, "data_size": 146240},
    {"object": "build/GL5E4F/obj/auto_01_800034A0_text.o", "name": "auto_01_800034A0_text", "autogenerated": true, "code_size": 1611360, "data_size": 0},
    {"object": "build/GL5E4F/obj/auto_00_80003100_init.o", "name": "auto_00_80003100_init", "autogenerated": true, "code_size": 928, "data_size": 0}
  ],
  "extract": [],
  "modules": [],
  "links": []
}
EOF
    fi
    
    echo
    echo "Split complete! Object files are in build/GL5E4F/obj/"
    echo
    echo "NOTE: Due to a dtk bug, ninja may try to re-run the split."
    echo "To build, use: ninja -t commands build/GL5E4F/main.dol"
    echo "Or manually assemble and link the object files."
else
    echo "[2/3] Split up to date, skipping..."
fi

# Step 3: Show status
echo "[3/3] Build status:"
echo
if [ -d "build/GL5E4F/obj" ]; then
    echo "Object files:"
    ls -lh build/GL5E4F/obj/*.o 2>/dev/null | awk '{print "  " $9 " (" $5 ")"}'
    echo
fi

if [ -f "build/GL5E4F/report.json" ]; then
    echo "Progress summary:"
    python3 -c "
import json
d = json.load(open('build/GL5E4F/report.json'))
measures = d.get('measures', {})
print(f\"  Total code: {int(measures.get('total_code', 0)):,} bytes\")
print(f\"  Total functions: {int(measures.get('total_functions', 0)):,}\")
print(f\"  Total units: {int(measures.get('total_units', 0))}\")
" 2>/dev/null || echo "  (progress info unavailable)"
fi

echo
echo "=== Build setup complete! ==="
echo
echo "Next steps:"
echo "  - Use objdiff to compare your code with the original"
echo "  - Start decompiling functions from build/GL5E4F/asm/"
echo "  - See README.md (Contributing section) for guidelines"
