#!/usr/bin/env python3
"""
Thin CLI for code matching progress.

Usage:
  python3 tools/matching_progress.py
  python3 tools/matching_progress.py --report
  python3 tools/matching_progress.py --json
"""

import argparse
import json
import sys
from pathlib import Path

import progress


def source_backed_unit_count() -> int:
    objdiff_path = Path(progress.PROJECT_ROOT) / "objdiff.json"
    if not objdiff_path.is_file():
        return 0

    with open(objdiff_path, "r", encoding="utf-8") as f:
        config = json.load(f)

    count = 0
    for unit in config.get("units", []):
        if unit.get("base_path") or unit.get("metadata", {}).get("source_path"):
            count += 1
    return count


def decompiled_source_count() -> int:
    src_root = Path(progress.PROJECT_ROOT) / "src"
    total = 0
    for suffix in ("*.c", "*.cc", "*.cpp"):
        total += sum(1 for _ in src_root.rglob(suffix))
    return total


def split_file_has_objects() -> bool:
    splits_path = Path(progress.PROJECT_ROOT) / "config" / "GL5E4F" / "splits.txt"
    if not splits_path.is_file():
        return False

    with open(splits_path, "r", encoding="utf-8") as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            if line == "Sections:":
                continue
            if line.startswith("."):
                continue
            return True
    return False


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Show current objdiff code matching progress",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--report", "-r",
        action="store_true",
        help="Auto-generate build/GL5E4F/report.json before display",
    )
    parser.add_argument(
        "--json", "-j",
        action="store_true",
        help="Emit matching progress as JSON",
    )
    args = parser.parse_args()

    if args.report and not progress.generate_report():
        sys.exit(1)

    matching = progress.read_report(progress.REPORT_PATH)
    if not matching:
        print(f"  {progress.red('!')} No report.json found. Run with --report or:")
        print("    ninja build/GL5E4F/report.json")
        print(f"  Expected at: {progress.REPORT_PATH}")
        sys.exit(1)

    source_backed_units = source_backed_unit_count()
    source_files = decompiled_source_count()
    has_object_splits = split_file_has_objects()

    if args.json:
        payload = {
            "matching": {
                "total_code": matching.get("total_code", 0),
                "matched_code": matching.get("matched_code", 0),
                "matched_code_percent": matching.get("matched_code_percent", 0),
                "fuzzy_match_percent": matching.get("fuzzy_match_percent", 0),
                "complete_code_percent": matching.get("complete_code_percent", 0),
                "total_functions": matching.get("total_functions", 0),
                "matched_functions": matching.get("matched_functions", 0),
                "total_units": matching.get("total_units", 0),
                "complete_units": matching.get("complete_units", 0),
                "total_data": matching.get("total_data", 0),
                "matched_data": matching.get("matched_data", 0),
                "matched_data_percent": matching.get("matched_data_percent", 0),
            },
            "source_backed_units": source_backed_units,
            "decompiled_source_files": source_files,
            "has_object_splits": has_object_splits,
        }
        print(json.dumps(payload, indent=2))
        return

    if source_backed_units == 0:
        print(f"  {progress.yellow('!')} No source-backed objdiff units are configured.")
        print("    objdiff.json currently contains only autogenerated section units,")
        print("    so game-code matched bytes/functions will read as 0 by construction.")
        print()

    print(f"  Tracked source-backed units: {source_backed_units}")
    print(f"  Decompiled source files:     {source_files}")
    print(f"  Object-level splits:         {'yes' if has_object_splits else 'no'}")
    print()

    progress.print_matching_progress(matching)


if __name__ == "__main__":
    main()
