#!/usr/bin/env python3
"""
Patch or synthesize build/GL5E4F/config.json from splits.txt.

This is a project-side workaround for dtk split panics. It preserves the
section-level fallback units needed by the current build flow, but also merges
in split-defined object units so configure.py / objdiff.json can see recovered
source files.
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

SRC_EXTS = (".c", ".cp", ".cpp")
MAKE_TARGET = Path(__file__).resolve().parent / "make_target_obj.py"


def regen_target_objects(file_entries: list[dict[str, Any]], src_dir: Path) -> None:
    """Build an objdiff target object for every decompiled source unit.

    Without this, objdiff/progress silently skips a unit until someone remembers
    to create build/<ver>/obj/<unit>.o by hand. Running it here (the SPLIT step)
    keeps matching progress in sync with the source on every configure.
    """
    for entry in file_entries:
        name = entry["name"]
        if not name.endswith(SRC_EXTS):
            continue
        if not (src_dir / name).exists():
            continue
        result = subprocess.run(
            [sys.executable, str(MAKE_TARGET), name],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            # Non-fatal: a unit may lack a clean asm slice yet. Keep configuring.
            sys.stderr.write(f"make_target_obj {name}: {result.stderr.strip()}\n")


DEFAULT_FALLBACK_UNITS = [
    {
        "object": "build/GL5E4F/obj/auto_07_8040B300_sdata2.o",
        "name": "auto_07_8040B300_sdata2",
        "autogenerated": True,
        "code_size": 0,
        "data_size": 2624,
    },
    {
        "object": "build/GL5E4F/obj/auto_06_8040A2C0_sbss.o",
        "name": "auto_06_8040A2C0_sbss",
        "autogenerated": True,
        "code_size": 0,
        "data_size": 4132,
    },
    {
        "object": "build/GL5E4F/obj/auto_05_80407A40_sdata.o",
        "name": "auto_05_80407A40_sdata",
        "autogenerated": True,
        "code_size": 0,
        "data_size": 10368,
    },
    {
        "object": "build/GL5E4F/obj/auto_04_801FD080_bss.o",
        "name": "auto_04_801FD080_bss",
        "autogenerated": True,
        "code_size": 0,
        "data_size": 2140604,
    },
    {
        "object": "build/GL5E4F/obj/auto_03_801B0640_data.o",
        "name": "auto_03_801B0640_data",
        "autogenerated": True,
        "code_size": 0,
        "data_size": 313888,
    },
    {
        "object": "build/GL5E4F/obj/auto_02_8018CB00_rodata.o",
        "name": "auto_02_8018CB00_rodata",
        "autogenerated": True,
        "code_size": 0,
        "data_size": 146240,
    },
    {
        "object": "build/GL5E4F/obj/auto_01_800034A0_text.o",
        "name": "auto_01_800034A0_text",
        "autogenerated": True,
        "code_size": 1611360,
        "data_size": 0,
    },
    {
        "object": "build/GL5E4F/obj/auto_00_80003100_init.o",
        "name": "auto_00_80003100_init",
        "autogenerated": True,
        "code_size": 928,
        "data_size": 0,
    },
]


def parse_splits(path: Path) -> list[dict[str, Any]]:
    file_entries: list[dict[str, Any]] = []
    current: dict[str, Any] | None = None
    start_re = re.compile(r"start:(0x[0-9A-Fa-f]+)")

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip()
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped == "Sections:":
            current = None
            continue
        if not line.startswith(("\t", " ")):
            if ":" in stripped:
                file_path = stripped.split(":", 1)[0].strip()
                if file_path.startswith("."):
                    current = None
                    continue
                current = {"name": file_path, "start": None}
                file_entries.append(current)
            continue
        if current is None:
            continue
        match = start_re.search(stripped)
        if match:
            value = int(match.group(1), 16)
            if current["start"] is None or value < current["start"]:
                current["start"] = value

    file_entries.sort(key=lambda entry: (entry["start"] is None, entry["start"], entry["name"]))
    return file_entries


def default_config() -> dict[str, Any]:
    return {
        "version": "1.8.3",
        "name": "main",
        "module_id": 0,
        "ldscript": "build/GL5E4F/ldscript.lcf",
        "entry": "__start",
        "units": list(DEFAULT_FALLBACK_UNITS),
        "extract": [],
        "modules": [],
        "links": [],
    }


def expected_object_path(build_dir: Path, file_name: str) -> str | None:
    obj_path = build_dir / "obj" / Path(file_name).with_suffix(".o")
    return str(obj_path) if obj_path.exists() else None


def main() -> None:
    parser = argparse.ArgumentParser(description="Patch config.json with split-defined units")
    parser.add_argument("--config-json", default="build/GL5E4F/config.json")
    parser.add_argument("--splits", default="config/GL5E4F/splits.txt")
    parser.add_argument("--build-dir", default="build/GL5E4F")
    args = parser.parse_args()

    config_path = Path(args.config_json)
    splits_path = Path(args.splits)
    build_dir = Path(args.build_dir)

    if config_path.exists():
        with open(config_path, "r", encoding="utf-8") as f:
            config = json.load(f)
    else:
        config = default_config()

    units = config.setdefault("units", [])
    units_by_name = {unit["name"]: unit for unit in units}

    split_entries = parse_splits(splits_path)
    # Keep objdiff target objects in sync with decompiled sources before wiring
    # their paths into the config below.
    regen_target_objects(split_entries, build_dir.parents[1] / "src")

    added = 0
    for entry in split_entries:
        name = entry["name"]
        object_path = expected_object_path(build_dir, name)
        if name in units_by_name:
            unit = units_by_name[name]
            if unit.get("object") is None and object_path is not None:
                unit["object"] = object_path
            continue
        units.append(
            {
                "object": object_path,
                "name": name,
                "autogenerated": False,
            }
        )
        units_by_name[name] = units[-1]
        added += 1

    config.setdefault("extract", [])
    config.setdefault("modules", [])
    config.setdefault("links", [])

    config_path.parent.mkdir(parents=True, exist_ok=True)
    with open(config_path, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2)
        f.write("\n")

    print(f"Patched {config_path} with {added} split-defined unit(s)")


if __name__ == "__main__":
    main()
